def additoin(x, y):
    x = 10
    y = 20
 
try:
    additoin(10 , 20)# call function inside try......
    print("Addition:", x + b)#b is not defined
   # additoin(10, 20)
except Exception  as e:
 print("'b' is not defined")






